eureka:
  instance:
    instance-id: "${spring.application.name}:${server.port}"
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000

zuul:
  prefix: /api
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 10000
  routes:
    authorization-server: /auth/**
    book-registry: /book/**
    composite-service: /cs/**
    picture-service: /picture/**
    review-service: /comment/**
    user-registry: /user/**

application:
  oauth2:
    client-id: "open-shelf"
    client-secret: "secret"
    signing-key: 987654321
