spring:
  datasource:
    url: jdbc:h2:mem:user-registry
  jpa:
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true

eureka:
  instance:
    instance-id: "${spring.application.name}:${server.port}"
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
